version: '3.8'

services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: management.franchises
      SPRING_R2DBC_URL: r2dbc:mysql://db:3306/management
      SPRING_R2DBC_USERNAME: root
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - db

  db:
    container_name: java_db
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"